import numpy as np
from scipy.optimize import fsolve
import matplotlib.pyplot as plt

e = 1
c = 1

def E_B(r_p, v_p, r_o, t):
    """
    Solve for the electric field vector generated by a charged particle, measured at r_o at time t.
    Arguments:
        r_p(t): function that returns the position of the particle at time t
        v_p(t): function that returns the velocity of the particle at time t
        r_o: position of measurement point
        t: time at which the measurement is taken
    """
    R = lambda tt: r_o - r_p(tt)
    t_r = np.array([fsolve(lambda t_p: t_p + np.linalg.norm(r_o[i,:] - r_p(t_p)) / c - t, t) for i in range(r_o.shape[0])])
    n = R(t_r) / np.expand_dims(np.linalg.norm(R(t_r), axis=1), axis=1)
    kap = 1 - np.dot(n, v_p(t_r) / c)
    E = e * ((n - v_p(t_r) / c) * (1 - np.linalg.norm(v_p(t_r) / c) ** 2) / np.expand_dims(kap ** 3 * np.linalg.norm(R(t_r), axis=1) ** 2, axis=1))
    B = np.linalg.cross(n, E)
    return E, B

def getEB(x, y, z, v):
    Gx, Gy, Gz = np.meshgrid(x, y, z)
    Gx = Gx.reshape(-1)
    Gy = Gy.reshape(-1)
    Gz = Gz.reshape(-1)
    G = np.vstack([Gx,Gy,Gz]).T
    def r_p(t):
        rx = v * t
        ry = np.zeros_like(rx)
        rz = np.zeros_like(ry)
        return np.hstack([rx, ry, rz])
    def v_p(t):
        return np.array([v, 0, 0])
    E, B = E_B(r_p, v_p, G, 0)
    Ex, Ey, Ez = E[:,0],E[:,1],E[:,2]
    Ex = Ex.reshape((x.shape[0], y.shape[0], z.shape[0]))
    Ey = Ey.reshape((x.shape[0], y.shape[0], z.shape[0]))
    Ez = Ez.reshape((x.shape[0], y.shape[0], z.shape[0]))
    Bx, By, Bz = B[:,0],B[:,1],B[:,2]
    Bx = Bx.reshape((x.shape[0], y.shape[0], z.shape[0]))
    By = By.reshape((x.shape[0], y.shape[0], z.shape[0]))
    Bz = Bz.reshape((x.shape[0], y.shape[0], z.shape[0]))
    return Ex, Ey, Ez, Bx, By, Bz

fig, axs = plt.subplots(2, 3)

v = 0.9 * c
x = np.linspace(-40, 40, 20)
y = np.linspace(-40, 40, 20)
z = np.linspace(0, 0, 1)
Ex, Ey, Ez, Bx, By, Bz = getEB(x, y, z, v)
N = np.hypot(Ex[:,:,0], Ey[:,:,0])
axs[0,0].quiver(x, y, Ex[:,:,0] / N, Ey[:,:,0] / N, N)
axs[0,0].set_xlabel('x')
axs[0,0].set_ylabel('y')
axs[0,0].set_title('E(x, y)')
N = np.hypot(Bx[:,:,0], By[:,:,0])
axs[1,0].quiver(x, y, Bx[:,:,0] / N, By[:,:,0] / N, N)
axs[1,0].set_xlabel('x')
axs[1,0].set_ylabel('y')
axs[1,0].set_title('B(x, y)')
z = np.linspace(-40, 40, 20)
y = np.linspace(-40, 40, 20)
x = np.linspace(0, 0, 1)
Ex, Ey, Ez, Bx, By, Bz = getEB(x, y, z, v)
N = np.hypot(Ey[0,:,:], Ez[0,:,:])
axs[0,1].quiver(y, z, Ey[0,:,:] / N, Ez[0,:,:] / N, N)
axs[0,1].set_xlabel('y')
axs[0,1].set_ylabel('z')
axs[0,1].set_title('E(y, z)')
N = np.hypot(By[0,:,:], Bz[0,:,:])
axs[1,1].quiver(y, z, By[0,:,:] / N, Bz[0,:,:] / N, N)
axs[1,1].set_xlabel('y')
axs[1,1].set_ylabel('z')
axs[1,1].set_title('B(y, z)')
x = np.linspace(-40, 40, 20)
z = np.linspace(-40, 40, 20)
y = np.linspace(0, 0, 1)
Ex, Ey, Ez, Bx, By, Bz = getEB(x, y, z, v)
N = np.hypot(Ex[:,0,:], Ez[:,0,:])
axs[0,2].quiver(x, z, Ex[:,0,:] / N, Ez[:,0,:] / N, N)
axs[0,2].set_xlabel('x')
axs[0,2].set_ylabel('z')
axs[0,2].set_title('E(x, z)')
N = np.hypot(Bx[:,0,:], Bz[:,0,:])
axs[1,2].quiver(x, z, Bx[:,0,:] / N, Bz[:,0,:] / N, N)
axs[1,2].set_xlabel('x')
axs[1,2].set_ylabel('z')
axs[1,2].set_title('B(x, z)')
fig.tight_layout()
plt.savefig(f'figs/{v:.3f}_E_B.svg',bbox_inches='tight')
# plt.show()

