import numpy as np
from scipy.optimize import fsolve
from scipy.integrate import quad
import matplotlib.pyplot as plt

e = 1
c = 1

def E_B(r_p, v_p, a_p, r_o, t):
    """
    Solve for the electric field vector generated by a charged particle, measured at r_o at time t.
    Arguments:
        r_p(t): function that returns the position of the particle at time t
        v_p(t): function that returns the velocity of the particle at time t
        r_o: position of measurement point
        t: time at which the measurement is taken
    """
    R = lambda r,tt: r - r_p(tt)
    t_r = np.array([fsolve(lambda t_p: t_p + np.linalg.norm(r_o[i,:] - r_p(t_p)) / c - t, t) for i in range(r_o.shape[0])])
    Es, Bs = [], []
    t_r = np.reshape(t_r, -1)
    for r,t_s in zip(r_o,t_r):
        n = R(r,t_s) / np.linalg.norm(R(r,t_s))
        kap = 1 - np.dot(n, v_p(t_s) / c)
        E = (e / c) * np.linalg.cross(n / (kap ** 3 * np.linalg.norm(R(r,t_s))), np.linalg.cross(n - v_p(t_s) / c, a_p(t_s) / c))
        B = np.linalg.cross(n, E)
        Es.append(E)
        Bs.append(B)
    return np.array(Es), np.array(Bs)

def getEBpar(x, y, z, v0, a, t):
    Gx, Gy, Gz = np.meshgrid(x, y, z)
    Gx = Gx.reshape(-1)
    Gy = Gy.reshape(-1)
    Gz = Gz.reshape(-1)
    G = np.vstack([Gx,Gy,Gz]).T
    def a_p(t):
        if t < 0:
            return np.array([0, 0, 0])
        return np.array([0, 0, a])
    k = v0 / np.sqrt(1 - (v0 / c) ** 2)
    def v_p(t):
        if t < 0:
            return np.array([v0, 0, 0])
        v_c = np.sqrt((a * t) ** 2 + k ** 2 / (c ** 2 + (a * t) ** 2 + k ** 2))
        vx = k * np.sqrt(1 - v_c ** 2)
        vz = (a * t / k) * vx
        return np.array([vx, 0, vz])
    def r_p(t):
        return np.array([quad(lambda tt: v_p(tt)[0], 0, t)[0], 0, quad(lambda tt: v_p(tt)[2], 0, t)[0]])
    E, B = E_B(r_p, v_p, a_p, G, t)
    Ex, Ey, Ez = E[:,0],E[:,1],E[:,2]
    Ex = Ex.reshape((x.shape[0], y.shape[0], z.shape[0]))
    Ey = Ey.reshape((x.shape[0], y.shape[0], z.shape[0]))
    Ez = Ez.reshape((x.shape[0], y.shape[0], z.shape[0]))
    Bx, By, Bz = B[:,0],B[:,1],B[:,2]
    Bx = Bx.reshape((x.shape[0], y.shape[0], z.shape[0]))
    By = By.reshape((x.shape[0], y.shape[0], z.shape[0]))
    Bz = Bz.reshape((x.shape[0], y.shape[0], z.shape[0]))
    return Ex, Ey, Ez, Bx, By, Bz

fig, axs = plt.subplots(2, 3)

v0 = 0.9 * c
a = 0.3 * c
t0 = 2
x = np.linspace(-2, 2, 20)
y = np.linspace(-2, 2, 20)
z = np.linspace(0, 0, 1)
Ex, Ey, Ez, Bx, By, Bz = getEBpar(x, y, z, v0, a, t0)
N = np.hypot(Ex[:,:,0], Ey[:,:,0])
axs[0,0].quiver(x, y, Ex[:,:,0] / N, Ey[:,:,0] / N, N)
axs[0,0].set_xlabel('x')
axs[0,0].set_ylabel('y')
axs[0,0].set_title('E(x, y)')
N = np.hypot(Bx[:,:,0], By[:,:,0])
axs[1,0].quiver(x, y, Bx[:,:,0] / N, By[:,:,0] / N, N)
axs[1,0].set_xlabel('x')
axs[1,0].set_ylabel('y')
axs[1,0].set_title('B(x, y)')
z = np.linspace(-2, 2, 20)
y = np.linspace(-2, 2, 20)
x = np.linspace(0, 0, 1)
Ex, Ey, Ez, Bx, By, Bz = getEBpar(x, y, z, v0, a, t0)
N = np.hypot(Ey[0,:,:], Ez[0,:,:])
axs[0,1].quiver(y, z, Ey[0,:,:] / N, Ez[0,:,:] / N, N)
axs[0,1].set_xlabel('y')
axs[0,1].set_ylabel('z')
axs[0,1].set_title('E(y, z)')
N = np.hypot(By[0,:,:], Bz[0,:,:])
axs[1,1].quiver(y, z, By[0,:,:] / N, Bz[0,:,:] / N, N)
axs[1,1].set_xlabel('y')
axs[1,1].set_ylabel('z')
axs[1,1].set_title('B(y, z)')
x = np.linspace(-2, 2, 20)
z = np.linspace(-2, 2, 20)
y = np.linspace(0, 0, 1)
Ex, Ey, Ez, Bx, By, Bz = getEBpar(x, y, z, v0, a, t0)
N = np.hypot(Ex[:,0,:], Ez[:,0,:])
axs[0,2].quiver(x, z, Ex[:,0,:] / N, Ez[:,0,:] / N, N)
axs[0,2].set_xlabel('x')
axs[0,2].set_ylabel('z')
axs[0,2].set_title('E(x, z)')
N = np.hypot(Bx[:,0,:], Bz[:,0,:])
axs[1,2].quiver(x, z, Bx[:,0,:] / N, Bz[:,0,:] / N, N)
axs[1,2].set_xlabel('x')
axs[1,2].set_ylabel('z')
axs[1,2].set_title('B(x, z)')
fig.tight_layout()
plt.savefig(f'figs/{v0:.3f}_t_{t0}_E_B_a_{a:.3f}_perp.svg',bbox_inches='tight')
# plt.show()

